apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-beta
  template:
    metadata:
      labels:
        app: nginx-beta
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: DATABASE_SERVERNAME
          value: "sql.example.local"
        - name: BACKEND_SERVERNAME
          value: "be.example.local"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-beta
spec:
  selector:
    app: nginx-beta
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP