apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-configmaps-files-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-configmaps-files-qa
  template:
    metadata:
      labels:
        app: nginx-configmaps-files-qa
    spec:
      volumes:
        - name: appconfig
          configMap:
            name: appconfigqa
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: appconfig
            mountPath: "/etc/appconfig"
