apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-configmaps-env-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-configmaps-env-prod
  template:
    metadata:
      labels:
        app: nginx-configmaps-env-prod
    spec:
      containers:
      - name: nginx
        image: nginx
        envFrom:
          - configMapRef:
              name: appconfigprod
        ports:
        - containerPort: 8080