apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-secrets-files
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-secrets-files
  template:
    metadata:
      labels:
        app: nginx-secrets-files
    spec:
      volumes:
        - name: appconfig
          secret:
            secretName: app1
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: appconfig
            mountPath: "/etc/appconfig"
