#https://docs.projectcalico.org/v3.6/getting-started/kubernetes/

- name: Init cluster
  command: kubeadm init  --node-name="{{ k8s_master_node_name }}" --pod-network-cidr="{{ k8s_master_pod_network_cidr }}"
  args:
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml

- name: Create .kube dir for {{ k8s_master_admin_user }} user
  file:
    path: "/home/{{ k8s_master_admin_user }}/.kube"
    state: directory
    owner: "{{ k8s_master_admin_user }}"
    group: "{{ k8s_master_admin_group }}"

- name: Copy kube config to {{ k8s_master_admin_user }} home .kube dir
  copy:
    src: /etc/kubernetes/admin.conf
    dest:  /home/{{ k8s_master_admin_user }}/.kube/config
    remote_src: yes
    owner: "{{ k8s_master_admin_user }}"
    group: "{{ k8s_master_admin_group }}"
    mode: 0660

- name: Install kuberouter CNI
  become: false
  ignore_errors: true
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml


- name: Generate join command
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubeadm token create --print-join-command
  register: join_command

- name: Copy join command for {{ k8s_cluster_name }} cluster to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./{{ k8s_cluster_name }}-join-command"

- name: enable autocomplete
  become: false
  lineinfile:
    path: /home/{{ k8s_master_admin_user }}/.bashrc
    line: "source <(kubectl completion bash)"
  ignore_errors: true

