apiVersion: batch/v1
kind: Job
metadata:
  name: pi-never
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["pe",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 2