
- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add k8s_common_admin_user user to docker group
  user:
    name: "{{ k8s_common_admin_user }}"
    group: docker

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"


- name: Configure node-ip {{ k8s_node_public_ip }} at kubelet
  lineinfile:
    path: '/etc/systemd/system/kubelet.service.d/10-kubeadm.conf'
    line: 'Environment="KUBELET_EXTRA_ARGS=--node-ip={{ k8s_node_public_ip }}"'
    regexp: 'KUBELET_EXTRA_ARGS='
    insertafter: '\[Service\]'
    state: present
  notify: restart kubelet

- name: Ensure the desired line exists in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{k8s_node_public_ip}} {{ inventory_hostname }}"
    create: yes  # Add the line if it doesn't exist

# - name: Remove file /etc/containerd/config.toml
#   file:
#     path: /etc/containerd/config.toml
#     state: absent

- name: Upload containerd toml config file
  template:
     src: containerd/config.toml.j2
     dest: /etc/containerd/config.toml

- name: Check that docker service is started
  service:
        name: docker
        state: restarted

- name: Restart containerd service
  service:
        name: containerd
        state: restarted