apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-customdns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-customdns
  template:
    metadata:
      labels:
        app: nginx-customdns
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 9.9.9.9
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-customdns
spec:
  selector:
    app: nginx-customdns
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
